baseurl = "https://cloud.aki.tips/"
title = "Aki.Tips"
author = "Akiyoshi Tsuchida"
copyright = "Akiyoshi Tsuchida"
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
googleAnalytics = "UA-131772017-2"

[Params]
author = "Akiyoshi Tsuchida"
introDescription = "都内でパブリッククラウドいじってる。"
siteIntroDescription = "パブリッククラウド系のメモ書き"
eyecatch = "images/home.png"